
mqtt:
  username: username
  password: password
  broker-url: tcp://${BROKER_DOMAIN:83.212.100.245}:${BROKER_PORT:1884}		# The address and port of your own server need to be changed
  clientID: summerschool2							            # This change is not optional, but different clients must not be the same
  timeout: 100
  keepalive: 100
  topics: summerschool/2021/topic/1, summerschool/2021/topic/2, summerschool/2021/topic/3
